### PR TITLE
feature: introduced not-equal operators for string.

### PR DESCRIPTION
**Pull request by cubicdaiya**
These operators are supposed for complete matching.

### CODE REVIEW

**Comment by sonots** [comment]
LGTM

**Comment by cubicdaiya** [comment]
@sonots Thank you for the review. Though I want to release v0.5.6 that includes this PR, can I release it?

**Comment by sonots** [comment]
Sure!

**Comment by cubicdaiya** [comment]
Released v0.5.6.

**Comment by sonots** [comment]
:tada:

**Pull request merged**
