### PR TITLE
added tests.

### PR DESCRIPTION
**Pull request by cubicdaiya**
Powered by [testify](https://github.com/stretchr/testify).

### CODE REVIEW

**Comment by cubicdaiya** [comment]
ping @sonots ?

**Comment by sonots** [comment]
I am not sure which testimg library is good to use, but adding tests are good.

**Comment by sonots** [comment]
it is okay to merge

**Comment by cubicdaiya** [comment]
Thanks. The reasons I want to use testify are below.

* Go has standard test package as [testing](https://golang.org/pkg/testing/). But it does not support assertion. OTOH, testify supports assertion. I like test with assertion.
* I'm testify user for over many years. It has been useful and stable.

**Comment by sonots** [comment]
Thanks, it sounds good to me.

**Pull request merged**
