### PR TITLE
expr: re-implemented by go package.

### PR DESCRIPTION
**Pull request by cubicdaiya**
More complicated expressions such as below are available.

```
diff = (ptime - uptime) * 1000
```

```bash
$ cat sample.ltsv
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
$ cat sample.ltsv | lltsv -k uri,ptime,uptime,diff_ms -e 'diff_ms = (ptime - uptime) * 1000'
uri:/hoge       ptime:0.120     uptime:0.050    diff_ms:70
uri:/foo        ptime:0.110     uptime:0.030    diff_ms:80
```

### CODE REVIEW

**Comment by sonots** [comment]
No problem to re-implement the parser.

**Comment by cubicdaiya** [comment]
> No problem to re-implement the parser.

@sonots I see. Thank you. I'll merge after testing a little more.

By the way, the implementaion on master/HEAD does not allow the space-trimed expression like below.

```bash
$ cat sample.ltsv | lltsv -k uri,ptime,uptime,diff_ms -e 'diff_ms = ptime-uptime'
2016/12/19 02:06:08 expression is invalid: diff_ms = ptime-uptime
```

But re-implemented version allows such as the expression.

**Comment by cubicdaiya** [comment]
Hi @sonots,

As I don't think there is any problem, I'll merge this PR. Do you have any opinion?

**Comment by sonots** [comment]
:+1:

**Pull request merged**
