### PR TITLE
sort keys by default.

### PR DESCRIPTION
**Pull request by cubicdaiya**
Previously lltsv outputed keys in random order when keys were not specified by -k. It's confusing. (On the other hand, this PR changes original behavior.)

### CODE REVIEW

**Comment by sonots** [comment]
Was that random order? I intended to be ordered same with LTSV file.

**Comment by cubicdaiya** [comment]
There is sample output below.

```
% lltsv --version
lltsv version 0.5.6
% wc -l sample.ltsv
 9497178 sample.ltsv
% cat sample.ltsv | head
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
% lltsv sample.ltsv | head
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
% lltsv sample.ltsv | head
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
uri:/foo        ptime:0.110     uptime:0.030
ptime:0.120     uptime:0.050    uri:/hoge
uri:/foo        ptime:0.110     uptime:0.030
uptime:0.050    uri:/hoge       ptime:0.120
uri:/foo        ptime:0.110     uptime:0.030
uri:/hoge       ptime:0.120     uptime:0.050
ptime:0.110     uptime:0.030    uri:/foo
%
```

If keys to output are not specified by `-k`, keys are possible to be output in random order like above. Because **keysInMap()** iterates key-map created by LTSV line and creates key-list per line. Unfortunately this key-list is not always ordered even if LTSV file is same. The keys of map are not ordered in Go1.3 or later. The reference is [here](https://golang.org/doc/go1.3#map).

So the **keysInMap()** creates key-list in random order and lltsv is possible to output records in random order when the keys to output by `-k` is not specified.

This PR kepts the order of keys in LTSV file constant even if the keys to output by `-k` is not specified.

**Comment by sonots** [comment]
Thank you for clarification. LGTM :+1:

**Comment by cubicdaiya** [comment]
🙇🏻

**Pull request merged**
